platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
 - name: cli-i18n
 - name: slack-attachment

outputs:
 - name: new-translations
 - name: validation-output

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    go version
    go get -u github.com/XenoPhex/i18n4go/i18n4go

    mkdir tmpdir

    pushd tmpdir
    unzip ../slack-attachment/translations.zip
    ls *.json | xargs -n 1 i18n4go -c verify-strings -v \
                                    --source-language en-us \
                                    -f ../cli-i18n/resources/en-us.all.json \
                                    --language-files | tee ../validaiton-output/out.txt
    popd

    mv tmpdir/*.json new-translations
