platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
 - name: cli-i18n
 - name: slack-attachment

outputs:
 - name: extracted-translations

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    go version
    go get -u github.com/XenoPhex/i18n4go/i18n4go

    mkdir tmpdir

    pushd tmpdir
    unzip ../slack-attachement/translations.zip
    i18n4go -c verify-strings --source-language en -f .../cli-i18n/resources/en-us.all.json --languages "de-de,en-us,es-es,fr-fr,it-it,ja-jp,ko-kr,pt-br,zh-hans,zh-han"
    popd

    mv tmpdir/*.json extracted-translations
