platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/i18n-base

inputs:
 - name: cli-i18n
 - name: slack-attachment

outputs:
 - name: new-translations
 - name: validation-output

run:
  path: bash
  args:
  - -c
  - |
    set -exo pipefail

    go version
    go get -u github.com/XenoPhex/i18n4go/i18n4go

    mkdir tmpdir

    pushd tmpdir
      unzip ../slack-attachment/translations.zip

      for file in $(ls cfcli/*.json); do
        file_base=$(basename "$file")
        jq -S --raw-output . $file > ../new-translations/$file_base
      done
    popd

    pushd new-translations
      ls *.json | xargs -n 1 i18n4go -c verify-strings -v \
                                      --source-language en-us \
                                      -f ../cli-i18n/resources/en-us.all.json \
                                      --language-files | tee ../validation-output/out.txt
    popd

    # format the filenames from en_US.all.json to en-us.all.json
    pushd new-translations
      for file in $(ls *.all.json); do
        mv $file $(echo $file | awk -F '_' '{print tolower($1) "-" tolower($2)}')
      done
    popd
