platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/i18n-base

inputs:
 - name: cli
 - name: cli-i18n

outputs:
 - name: updated-translation-files

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    go version
    go get -u github.com/XenoPhex/i18n4go/i18n4go

    mkdir tmpdir

    IGNORE_FILES_REGEX=".*test.go|.*resources.go|fake.*\.go|template.go"

    i18n4go -c extract-strings -e cli/strings/excluded.json -s cli/strings/specialStrings.json -o tmpdir -d cli/command -r --ignore-regexp $IGNORE_FILES_REGEX
    i18n4go -c extract-strings -e cli/strings/excluded.json -s cli/strings/specialStrings.json -o tmpdir -d cli/cf -r --ignore-regexp $IGNORE_FILES_REGEX
    i18n4go -c merge-strings -d tmpdir

    i18n4go -c create-translations -f tmpdir/en.all.json -languages "de-de,en-us,es-es,fr-fr,it-it,ja-jp,ko-kr,pt-br,zh-hans,zh-hant"

    go run cli-i18n/bin/reformat_translated_json.go ./

    mv *all.json updated-translation-files

    mv en-us.all.json cli-i18n/resources/en-us.all.json
    pushd cli-i18n
      git config --global user.email "cf-cli-eng@pivotal.io"
      git config --global user.name "cf-cli-eng"

      git add ./resources/en-us.all.json
      git commit -m "Updating en-us translation file"
    popd
