platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
 - name: cli
 - name: cli-i18n

outputs:
 - name: updated-translation-files

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    go version
    go get -u github.com/XenoPhex/i18n4go/i18n4go

    mkdir tmpdir

    IGNORE_FILES_REGEX=".*test.go|.*resources.go|fake.*\.go|template.go"

    i18n4go -c extract-strings -e cli/strings/excluded.json -s cli/strings/specialStrings.json -o tmpdir -d cli/command -r --ignore-regexp $IGNORE_FILES_REGEX
    i18n4go -c extract-strings -e cli/strings/excluded.json -s cli/strings/specialStrings.json -o tmpdir -d cli/cf -r --ignore-regexp $IGNORE_FILES_REGEX
    i18n4go -c merge-strings -d tmpdir

    i18n4go -c create-translations -f tmpdir/en.all.json -languages "de-de,en-us,es-es,fr-fr,it-it,ja-jp,ko-kr,pt-br,zh-hans,zh-hant"

    go run cli-i18n/bin/reformat_translated_json.go ./

    mv *all.json updated-translation-files
