platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
 - name: updated-translation-files

outputs:
 - name: outputs

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    zip outputs/all.json.zip updated-translation-files/*all.json
