platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/i18n-base

inputs:
 - name: updated-translation-files

outputs:
 - name: outputs

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cd updated-translation-files
    zip ../outputs/all.json.zip *all.json
