---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    ignore_paths:
    - ci
    - integration

- name: cli-i18n
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-i18n
    branch: master
    private_key: {{cli-i18n-github-private-key}}
    trigger: true

- name: upload-translation-zip
  type: s3
  source:
    bucket: cf-cli-i18n
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: all.json.zip
    region_name: ap-southeast-1

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

groups:
- name: cli
  jobs:
  - extract-i18n

jobs:
- name: extract-i18n
  serial: true
  plan:
  - aggregate:
    - get: cli
    - get: cli-i18n
  - do:
    - task: extract-i18n
      file: cli-i18n/ci/tasks/generate-i18n-json.yml
    - task: package-i18n
      file: cli-i18n/ci/tasks/package-i18n-json.yml
    - put: upload-translation-zip
      params:
        file: outputs/all.json.zip
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-eng'
         text: "extract i18n JSON failed :("
    on_success:
      put: slack-alert
      params:
        channel: '#cli-eng'
        text: |
          NEW i18n JSON files ready for translation: https://s3-ap-southeast-1.amazonaws.com/cf-cli-i18n/all.json.zip
