---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    ignore_paths:
    - ci
    - integration

- name: cli-i18n
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-i18n
    branch: master
    private_key: {{cli-i18n-github-private-key}}
    trigger: true

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

groups:
- name: cli
  jobs:
  - extract-i18n

jobs:
- name: extract-i18n
  serial: true
  plan:
  - aggregate:
    - get: cli
    - get: cli-i18n
  - task: extract-i18n
    file: cli-i18n/ci/tasks/generate-i18n-json.yml
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-eng'
         text: "extract i18n JSON failed :("
    on_success:
      put: slack-alert
      params:
        channel: '#cli-eng'
        text: |
          NEW i18n JSON files ready for translation
          Find a tarball in our Google Drive:
          <add-link-to-tarball-here>
          For access please email: cf-cli-eng@pivotal.io
