---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    ignore_paths:
    - ci
    - integration

- name: cli-i18n
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-i18n
    branch: master
    private_key: {{cli-i18n-github-private-key}}
    trigger: true

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

- name: monthly
  type: time
  source: {interval: 700h}

groups:
- name: cli
  jobs:
  - build-i18n

jobs:
- name: build-i18n
  serial: true
  plan:
  - aggregate:
    - get: cli
    - get: cli-i18n
    - get: monthly
      trigger: true
  - task: build-i18n
    file: cli-i18n/ci/tasks/generate-i18n-json.yml
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-firehose'
         text: "build i18n JSON failed :("
    on_success:
       put: slack-alert
       params:
         channel: '#cli-firehose'
         text: "NEW i18n JSON files ready for translations"
    ensure:
      put: cli-i18n
      params:
        repository: updated-cli-i18n
        rebase: true
